# Generated by Django 5.0.11 on 2025-07-23 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='s3fileobject',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.uploadsession'),
        ),
        migrations.AddIndex(
            model_name='aclpermissions',
            index=models.Index(fields=['content_type', 'object_id'], name='storage_acl_content_80204b_idx'),
        ),
        migrations.AddIndex(
            model_name='s3resourcelocation',
            index=models.Index(fields=['resource_pid'], name='storage_s3r_resourc_21badb_idx'),
        ),
        migrations.AddIndex(
            model_name='s3resourcelocation',
            index=models.Index(fields=['content_type', 'object_id'], name='storage_s3r_content_47d3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['user', 'status'], name='storage_upl_user_id_0374e7_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['created_at'], name='storage_upl_created_8d2374_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['import_type'], name='storage_upl_import__2c966d_idx'),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['session'], name='storage_s3f_session_9eb76b_idx'),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['status'], name='storage_s3f_status_f88fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['s3_key'], name='storage_s3f_s3_key_417986_idx'),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['source_csv_file', 'source_row_number'], name='storage_s3f_source__f79983_idx'),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['related_resource'], name='storage_s3f_related_8b9659_idx'),
        ),
    ]
