# Generated by Django 5.0.11 on 2025-05-28 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='s3fileobject',
            name='related_resource_uri',
            field=models.CharField(blank=True, help_text='URI of the metadata resource this file is associated with', max_length=512),
        ),
        migrations.AddField(
            model_name='s3fileobject',
            name='s3_url',
            field=models.URLField(blank=True, help_text='Full S3 URL to access this file', max_length=1024),
        ),
        migrations.AddField(
            model_name='s3fileobject',
            name='source_column_name',
            field=models.CharField(blank=True, help_text='Column name in the CSV that contained this file reference', max_length=255),
        ),
        migrations.AddField(
            model_name='s3fileobject',
            name='source_csv_file',
            field=models.CharField(blank=True, help_text='Name of the CSV file this file was referenced from', max_length=512),
        ),
        migrations.AddField(
            model_name='s3fileobject',
            name='source_row_number',
            field=models.IntegerField(blank=True, help_text='Row number in the CSV where this file was referenced', null=True),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='base_uri',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='import_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='import_type',
            field=models.CharField(choices=[('csv_import', 'CSV Import'), ('file_upload', 'File Upload'), ('zip_import', 'ZIP Import')], default='csv_import', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='s3_base_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='s3_bucket',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['source_csv_file', 'source_row_number'], name='storage_s3f_source__f79983_idx'),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['related_resource_uri'], name='storage_s3f_related_b05bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['import_type'], name='storage_upl_import__2c966d_idx'),
        ),
    ]
