# Generated by Django 5.0.11 on 2025-05-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_remove_resource_resource_type_consistency_and_more'),
        ('storage', '0002_s3fileobject_related_resource_uri_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='s3fileobject',
            name='storage_s3f_related_b05bc2_idx',
        ),
        migrations.RemoveField(
            model_name='s3fileobject',
            name='related_resource_uri',
        ),
        migrations.AddField(
            model_name='s3fileobject',
            name='related_resource',
            field=models.ForeignKey(blank=True, help_text='Direct link to the metadata resource this file is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.resource'),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['related_resource'], name='storage_s3f_related_8b9659_idx'),
        ),
    ]
