# Generated by Django 5.0.11 on 2025-06-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_remove_mapping_metadata_ma_organiz_1e991b_idx_and_more'),
        ('storage', '0003_remove_s3fileobject_storage_s3f_related_b05bc2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='s3fileobject',
            name='storage_s3f_session_fe5e7a_idx',
        ),
        migrations.AlterField(
            model_name='s3fileobject',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.uploadsession'),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['session'], name='storage_s3f_session_9eb76b_idx'),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['status'], name='storage_s3f_status_f88fa2_idx'),
        ),
    ]
