# Generated by Django 5.0.11 on 2025-05-14 08:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CIDOCClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_primitive', models.BooleanField(default=False, help_text='If True, this class represents a primitive value type (E59, E60, etc.)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent_classes', models.ManyToManyField(blank=True, related_name='child_classes', to='cidoc.cidocclass')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CIDOC Class',
                'verbose_name_plural': 'CIDOC Classes',
            },
        ),
        migrations.CreateModel(
            name='CIDOCProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_functional', models.BooleanField(default=False, help_text='Property can have at most one value')),
                ('is_symmetric', models.BooleanField(default=False, help_text='If A relates to B, then B relates to A')),
                ('is_transitive', models.BooleanField(default=False, help_text='If A relates to B and B to C, then A relates to C')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('domain_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_properties', to='cidoc.cidocclass')),
                ('inverse_property', models.ForeignKey(blank=True, help_text='The inverse property (e.g., P1i for P1)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inverse_of', to='cidoc.cidocproperty')),
                ('parent_properties', models.ManyToManyField(blank=True, related_name='child_properties', to='cidoc.cidocproperty')),
                ('range_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_properties', to='cidoc.cidocclass')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CIDOC Property',
                'verbose_name_plural': 'CIDOC Properties',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uri', models.URLField(help_text='Uniform Resource Identifier for this resource', max_length=512, unique=True)),
                ('source', models.CharField(blank=True, help_text='Source or origin of this resource', max_length=255)),
                ('value', models.TextField(blank=True, help_text='Value when this resource represents a literal', null=True)),
                ('is_literal', models.BooleanField(default=False, help_text='Whether this resource represents a literal value')),
                ('datatype', models.CharField(blank=True, help_text='Datatype URI for literal values (e.g., xsd:string, xsd:integer)', max_length=255, null=True)),
                ('language', models.CharField(blank=True, help_text="Language tag for language-tagged string literals (e.g., 'en', 'fr')", max_length=10, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_triples', to='cidoc.resource')),
                ('predicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicate_triples', to='cidoc.resource')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_triples', to='cidoc.resource')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['subject', 'predicate'], name='cidoc_tripl_subject_69b4b6_idx'), models.Index(fields=['object'], name='cidoc_tripl_object__a140df_idx')],
            },
        ),
    ]
