# Generated by Django 5.0.11 on 2025-04-06 14:25

import arkumu.cidoc.models.entities
import arkumu.cidoc.models.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CIDOCClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_primitive', models.BooleanField(default=False, help_text='If True, this class represents a primitive value type (E59, E60, etc.)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent_classes', models.ManyToManyField(blank=True, related_name='child_classes', to='cidoc.cidocclass')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CIDOC Class',
                'verbose_name_plural': 'CIDOC Classes',
            },
        ),
        migrations.CreateModel(
            name='CIDOCEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crm_class', models.CharField(max_length=50, validators=[arkumu.cidoc.models.validators.validate_cidoc_entity])),
                ('age_node_id', models.CharField(max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CIDOCGraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CIDOCProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_functional', models.BooleanField(default=False, help_text='Property can have at most one value')),
                ('is_symmetric', models.BooleanField(default=False, help_text='If A relates to B, then B relates to A')),
                ('is_transitive', models.BooleanField(default=False, help_text='If A relates to B and B to C, then A relates to C')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('domain_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_properties', to='cidoc.cidocclass')),
                ('inverse_property', models.ForeignKey(blank=True, help_text='The inverse property (e.g., P1i for P1)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inverse_of', to='cidoc.cidocproperty')),
                ('parent_properties', models.ManyToManyField(blank=True, related_name='child_properties', to='cidoc.cidocproperty')),
                ('range_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_properties', to='cidoc.cidocclass')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CIDOC Property',
                'verbose_name_plural': 'CIDOC Properties',
            },
        ),
        migrations.CreateModel(
            name='CIDOCEntityProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_data', models.JSONField(null=True)),
                ('age_node_id', models.CharField(max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidoc.cidocentity')),
                ('readable_by_groups', models.ManyToManyField(blank=True, related_name='can_read_entity_properties', to='auth.group')),
                ('readable_by_users', models.ManyToManyField(blank=True, related_name='can_read_entity_properties', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('writable_by_groups', models.ManyToManyField(blank=True, related_name='can_write_entity_properties', to='auth.group')),
                ('writable_by_users', models.ManyToManyField(blank=True, related_name='can_write_entity_properties', to=settings.AUTH_USER_MODEL)),
                ('cidoc_property', models.ForeignKey(error_messages={'unique': 'This property already exists for this entity'}, on_delete=django.db.models.deletion.PROTECT, to='cidoc.cidocproperty')),
            ],
            bases=(models.Model, arkumu.cidoc.models.entities.CIDOCPermissionMixin),
        ),
        migrations.AddField(
            model_name='cidocentity',
            name='properties',
            field=models.ManyToManyField(through='cidoc.CIDOCEntityProperty', to='cidoc.cidocproperty'),
        ),
        migrations.CreateModel(
            name='CIDOCRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(max_length=50)),
                ('age_edge_id', models.CharField(max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='cidoc.cidocentity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='cidoc.cidocentity')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CIDOCRelationshipProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_data', models.JSONField(null=True)),
                ('age_node_id', models.CharField(max_length=50, null=True)),
                ('cidoc_property', models.ForeignKey(error_messages={'unique': 'This property already exists for this relationship'}, on_delete=django.db.models.deletion.PROTECT, to='cidoc.cidocproperty')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('readable_by_groups', models.ManyToManyField(blank=True, related_name='can_read_relationship_properties', to='auth.group')),
                ('readable_by_users', models.ManyToManyField(blank=True, related_name='can_read_relationship_properties', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidoc.cidocrelationship')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('writable_by_groups', models.ManyToManyField(blank=True, related_name='can_write_relationship_properties', to='auth.group')),
                ('writable_by_users', models.ManyToManyField(blank=True, related_name='can_write_relationship_properties', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, arkumu.cidoc.models.entities.CIDOCPermissionMixin),
        ),
        migrations.AddField(
            model_name='cidocrelationship',
            name='properties',
            field=models.ManyToManyField(related_name='relationship_properties', through='cidoc.CIDOCRelationshipProperty', to='cidoc.cidocproperty'),
        ),
        migrations.AddConstraint(
            model_name='cidocentityproperty',
            constraint=models.UniqueConstraint(fields=('entity', 'cidoc_property'), name='unique_entity_property'),
        ),
        migrations.AddConstraint(
            model_name='cidocrelationshipproperty',
            constraint=models.UniqueConstraint(fields=('relationship', 'cidoc_property'), name='unique_relationship_property'),
        ),
    ]
