# Generated by Django 5.0.11 on 2025-05-14 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidoc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='datatype',
            new_name='literal_datatype',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='language',
            new_name='literal_language',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='value',
            new_name='literal_value',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_literal',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('IRI', 'IRI Identified Resource'), ('CLASS', 'Class'), ('PROPERTY', 'Property'), ('LITERAL', 'Literal')], default='IRI', help_text='Type of the resource (IRI, Class, Property, or Literal)', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uri',
            field=models.URLField(blank=True, help_text='Uniform Resource Identifier for this resource', max_length=512, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('resource_type', 'LITERAL'), ('literal_value__isnull', False)), models.Q(models.Q(('resource_type', 'LITERAL'), _negated=True), ('uri__isnull', False)), _connector='OR'), name='resource_type_consistency'),
        ),
    ]
