# Generated by Django 5.0.11 on 2025-04-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('identifier_type', models.CharField(max_length=50)),
                ('source_system', models.CharField(max_length=100)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='cidoc.cidocentity')),
            ],
        ),
    ]
