# Generated by Django 5.0.11 on 2025-05-09 12:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cidoc', '0002_externalidentifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cidocrelationship',
            name='readable_by_groups',
            field=models.ManyToManyField(blank=True, related_name='can_read_relationships', to='auth.group'),
        ),
        migrations.AddField(
            model_name='cidocrelationship',
            name='readable_by_users',
            field=models.ManyToManyField(blank=True, related_name='can_read_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cidocrelationship',
            name='writable_by_groups',
            field=models.ManyToManyField(blank=True, related_name='can_write_relationships', to='auth.group'),
        ),
        migrations.AddField(
            model_name='cidocrelationship',
            name='writable_by_users',
            field=models.ManyToManyField(blank=True, related_name='can_write_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SourceTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('field', models.CharField(blank=True, max_length=100)),
                ('import_batch', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CIDOCEntityRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, help_text='Human-readable name/label for the entity', max_length=255)),
                ('external_id', models.CharField(blank=True, help_text='ID from external system if applicable', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='cidoc.cidocclass')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='cidoc.sourcetracking')),
            ],
            options={
                'verbose_name': 'CIDOC Entity Registry',
                'verbose_name_plural': 'CIDOC Entity Registries',
            },
        ),
        migrations.CreateModel(
            name='CIDOCData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_data', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidoc.cidocproperty')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_as_subject', to='cidoc.cidocentityregistry')),
                ('target_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_as_target', to='cidoc.cidocentityregistry')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_entries', to='cidoc.sourcetracking')),
            ],
        ),
        migrations.AddIndex(
            model_name='sourcetracking',
            index=models.Index(fields=['institution', 'field'], name='cidoc_sourc_institu_74a620_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcetracking',
            index=models.Index(fields=['import_batch'], name='cidoc_sourc_import__d827a3_idx'),
        ),
        migrations.AddIndex(
            model_name='cidocentityregistry',
            index=models.Index(fields=['entity_class'], name='cidoc_cidoc_entity__b9c157_idx'),
        ),
        migrations.AddIndex(
            model_name='cidocentityregistry',
            index=models.Index(fields=['external_id'], name='cidoc_cidoc_externa_4e5e59_idx'),
        ),
        migrations.AddIndex(
            model_name='cidocentityregistry',
            index=models.Index(fields=['label'], name='cidoc_cidoc_label_89d7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='cidocdata',
            index=models.Index(fields=['entity'], name='cidoc_cidoc_entity__d088ba_idx'),
        ),
        migrations.AddIndex(
            model_name='cidocdata',
            index=models.Index(fields=['target_entity'], name='cidoc_cidoc_target__450e71_idx'),
        ),
        migrations.AddIndex(
            model_name='cidocdata',
            index=models.Index(fields=['property'], name='cidoc_cidoc_propert_9fd62b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cidocdata',
            constraint=models.UniqueConstraint(fields=('entity', 'property', 'target_entity'), name='unique_entity_property_target'),
        ),
    ]
