# Generated by Django 5.0.11 on 2025-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidoc', '0002_rename_datatype_resource_literal_datatype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='source_field',
            field=models.TextField(blank=True, help_text='Original value from the source data field', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='source',
            field=models.CharField(blank=True, help_text="Source or origin of this resource (e.g., the institution like 'FUK')", max_length=255),
        ),
    ]
