# Generated by Django 5.0.11 on 2025-07-23 09:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Unique identifier for the organization (used in URLs and Shibboleth mapping)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code can only contain letters, numbers, hyphens and underscores.', regex='^[a-zA-Z0-9_-]+$')])),
                ('domain', models.CharField(blank=True, help_text='Email domain for automatic user assignment (e.g., "example.edu")', max_length=255)),
                ('shibboleth_entity_id', models.CharField(blank=True, help_text='Shibboleth Identity Provider entity ID', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive organizations cannot be accessed by users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Internal notes about this organization')),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email for this organization', max_length=254)),
                ('contact_name', models.CharField(blank=True, help_text='Primary contact person for this organization', max_length=255)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='users_organ_code_178c64_idx'), models.Index(fields=['domain'], name='users_organ_domain_2e02e6_idx'), models.Index(fields=['is_active', 'created_at'], name='users_organ_is_acti_f845ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
                ('role', models.CharField(choices=[('researcher', 'Researcher'), ('archivist', 'Media Documentarian'), ('manager', 'Manager'), ('super_manager', 'Super Manager'), ('system_admin', 'System Administrator')], default='researcher', max_length=20)),
                ('auth_source', models.CharField(choices=[('local', 'Local Authentication'), ('shibboleth', 'Shibboleth Federation')], default='local', max_length=20)),
                ('shibboleth_eppn', models.CharField(blank=True, help_text='eduPersonPrincipalName from Shibboleth', max_length=255, null=True, unique=True)),
                ('shibboleth_persistent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('shibboleth_affiliation', models.CharField(blank=True, help_text='eduPersonScopedAffiliation from Shibboleth', max_length=255)),
                ('last_shibboleth_login', models.DateTimeField(blank=True, null=True)),
                ('is_federated_user', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.organization')),
            ],
            options={
                'permissions': [('can_access_admin_backend', 'Can access admin backend'), ('can_import_universal', 'Can import via universal importer'), ('can_manage_metadata', 'Can manage global metadata'), ('can_reset_database', 'Can reset database'), ('can_manage_org_users', 'Can manage organization users'), ('can_transfer_to_public', 'Can transfer data to public'), ('can_approve_public_access', 'Can approve resources for public catalog display'), ('can_view_cross_university_public', 'Can view public information from other universities'), ('can_link_cross_university', 'Can link own resources with public resources from other universities')],
                'indexes': [models.Index(fields=['shibboleth_eppn'], name='users_user_shibbol_29f3fa_idx'), models.Index(fields=['organization', 'role'], name='users_user_organiz_fdf17c_idx'), models.Index(fields=['auth_source'], name='users_user_auth_so_ee54e0_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
