# Generated by Django 5.0.11 on 2025-06-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='auth_source',
            field=models.CharField(choices=[('local', 'Local Authentication'), ('shibboleth', 'Shibboleth Federation')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_federated_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_shibboleth_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('researcher', 'Researcher'), ('archivist', 'Archivist'), ('data_admin', 'Data Administrator'), ('org_admin', 'Organization Administrator'), ('system_admin', 'System Administrator')], default='researcher', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='shibboleth_affiliation',
            field=models.CharField(blank=True, help_text='eduPersonScopedAffiliation from Shibboleth', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='shibboleth_eppn',
            field=models.CharField(blank=True, help_text='eduPersonPrincipalName from Shibboleth', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shibboleth_persistent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('shibboleth_entity_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='users_organ_code_178c64_idx'), models.Index(fields=['domain'], name='users_organ_domain_2e02e6_idx')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.organization'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['shibboleth_eppn'], name='users_user_shibbol_29f3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role'], name='users_user_organiz_fdf17c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['auth_source'], name='users_user_auth_so_ee54e0_idx'),
        ),
    ]
