# Generated by Django 5.0.11 on 2025-06-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_auth_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_access_admin_backend', 'Can access admin backend'), ('can_import_universal', 'Can import via universal importer'), ('can_manage_metadata', 'Can manage global metadata'), ('can_reset_database', 'Can reset database'), ('can_view_org_data', 'Can view organization data'), ('can_edit_org_data', 'Can edit organization data'), ('can_delete_org_data', 'Can delete organization data'), ('can_manage_org_users', 'Can manage organization users'), ('can_transfer_to_public', 'Can transfer data to public')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('researcher', 'Researcher'), ('archivist', 'Media Documentarian'), ('manager', 'Manager'), ('super_manager', 'Super Manager'), ('system_admin', 'System Administrator')], default='researcher', max_length=20),
        ),
    ]
