# Generated by Django 5.0.11 on 2025-06-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_access_admin_backend', 'Can access admin backend'), ('can_import_universal', 'Can import via universal importer'), ('can_manage_metadata', 'Can manage global metadata'), ('can_reset_database', 'Can reset database'), ('can_manage_org_users', 'Can manage organization users'), ('can_transfer_to_public', 'Can transfer data to public'), ('can_approve_public_access', 'Can approve resources for public catalog display'), ('can_view_cross_university_public', 'Can view public information from other universities'), ('can_link_cross_university', 'Can link own resources with public resources from other universities')]},
        ),
    ]
