# Generated by Django 5.0.11 on 2025-07-11 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email for this organization', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Primary contact person for this organization', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='Internal notes about this organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(help_text='Unique identifier for the organization (used in URLs and Shibboleth mapping)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code can only contain letters, numbers, hyphens and underscores.', regex='^[a-zA-Z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='domain',
            field=models.CharField(blank=True, help_text='Email domain for automatic user assignment (e.g., "example.edu")', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive organizations cannot be accessed by users'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='shibboleth_entity_id',
            field=models.CharField(blank=True, help_text='Shibboleth Identity Provider entity ID', max_length=255),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'created_at'], name='users_organ_is_acti_f845ba_idx'),
        ),
    ]
