# Generated by Django 5.0.11 on 2025-07-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_organization_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('rsh', 'Robert Schumann Hochschule Düsseldorf'), ('khm', 'Kunsthochschule für Medien Köln'), ('fuk', 'Folkwang Universität der Künste'), ('hmt', 'Hochschule für Musik und Tanz Köln'), ('det', 'Hochschule für Musik Detmold'), ('other', 'Other Institution')], help_text='Select from predefined institution types or choose "Other"', max_length=20),
        ),
    ]
