# Generated by Django 5.0.11 on 2025-07-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_organization_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organization_type',
        ),
    ]
