# Generated by Django 5.0.11 on 2025-02-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akteur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_by', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('orcid', models.CharField(blank=True, max_length=255, null=True)),
                ('normdaten', models.TextField(blank=True, null=True)),
                ('webseiten', models.TextField(blank=True, null=True)),
                ('kurzbiografie_de', models.TextField(blank=True, null=True)),
                ('kommentar_de', models.TextField(blank=True, null=True)),
                ('kurzbiografie_en', models.TextField(blank=True, null=True)),
                ('kommentar_en', models.TextField(blank=True, null=True)),
                ('geschlecht', models.BigIntegerField(blank=True, null=True)),
                ('kontakt_emails', models.CharField(blank=True, max_length=255, null=True)),
                ('kontakt_telefon', models.CharField(blank=True, max_length=255, null=True)),
                ('kontakt_postanschrift', models.CharField(blank=True, max_length=255, null=True)),
                ('nicht_oeffentliche_namen', models.CharField(blank=True, max_length=255, null=True)),
                ('nicht_oeffentliche_namen_erlaeuterung', models.CharField(blank=True, max_length=255, null=True)),
                ('alternativer_namen', models.TextField(blank=True, null=True)),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
                ('lccnid', models.CharField(blank=True, max_length=255, null=True)),
                ('viafid', models.CharField(blank=True, max_length=255, null=True)),
                ('wikidataid', models.CharField(blank=True, max_length=255, null=True)),
                ('spaetster_wirkungsbegin', models.CharField(blank=True, max_length=255, null=True)),
                ('spaetestes_geburtsdatum', models.CharField(blank=True, max_length=255, null=True)),
                ('fruehstes_sterbedatum', models.CharField(blank=True, max_length=255, null=True)),
                ('fruehstes_wirkungsende', models.CharField(blank=True, max_length=255, null=True)),
                ('fruehstes_geburtsdatum', models.CharField(blank=True, max_length=255, null=True)),
                ('spaetestes_sterbedatum', models.CharField(blank=True, max_length=255, null=True)),
                ('fruehster_wirkungsbegin', models.CharField(blank=True, max_length=255, null=True)),
                ('spaetstes_wirkungsende', models.CharField(blank=True, max_length=255, null=True)),
                ('vorangestellter_titel', models.CharField(blank=True, max_length=255, null=True)),
                ('nachgestellter_titel', models.CharField(blank=True, max_length=255, null=True)),
                ('datensatz_id_einlieferer', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created_einlieferer', models.DateTimeField(blank=True, null=True)),
                ('date_modified_einlieferer', models.DateTimeField(blank=True, null=True)),
                ('kommentar_intern', models.TextField(blank=True, null=True)),
                ('andere_normdaten', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'akteur',
            },
        ),
        migrations.CreateModel(
            name='AkteurMitwirkungsRolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akteur_berufe_taetigkeiten_id', models.BigIntegerField()),
                ('mitwirkungs_rolle_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'akteur_mitwirkungs_rolle',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('persisted_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('property_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('persisted_object_version', models.BigIntegerField(blank=True, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='Base64DecodedMultipartFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
            ],
            options={
                'db_table': 'base64decoded_multipart_file',
            },
        ),
        migrations.CreateModel(
            name='DataImporter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('source_table', models.CharField(max_length=255)),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('data_destination_id', models.CharField(blank=True, max_length=255, null=True)),
                ('data_source_id', models.CharField(max_length=255)),
                ('destination_table', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField()),
                ('contributor', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'data_importer',
            },
        ),
        migrations.CreateModel(
            name='DigitalesObjektLizenz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('anzeige_text_de', models.CharField(blank=True, max_length=255, null=True)),
                ('rechtestatment', models.CharField(max_length=255)),
                ('lizenz_text_en', models.TextField(blank=True, null=True)),
                ('lizenz_text_de', models.TextField(blank=True, null=True)),
                ('bezeichnung_de', models.CharField(max_length=255)),
                ('bezeichnung_en', models.CharField(max_length=255)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('anzeige_text_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'digitales_objekt_lizenz',
            },
        ),
        migrations.CreateModel(
            name='Eigenschaft',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
                ('wikidataid', models.CharField(max_length=255)),
                ('description_de', models.CharField(max_length=512)),
                ('description_en', models.CharField(max_length=512)),
                ('type', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eigenschaft',
            },
        ),
        migrations.CreateModel(
            name='Equipmentart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('aatid', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
                ('wikidataid', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'equipmentart',
            },
        ),
        migrations.CreateModel(
            name='Ereignis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('normdatei', models.CharField(blank=True, max_length=255, null=True)),
                ('stimmung_in_hertz', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('ende_estimated', models.BooleanField(blank=True, null=True)),
                ('beginn', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
                ('ende_date', models.DateTimeField(blank=True, null=True)),
                ('auffuehrungstonart', models.CharField(blank=True, max_length=255, null=True)),
                ('beginn_estimated', models.BooleanField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('beginn_date', models.DateTimeField(blank=True, null=True)),
                ('ende', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_by', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('kommentar_de', models.TextField(blank=True, null=True)),
                ('wikidataid', models.CharField(blank=True, max_length=255, null=True)),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
                ('kommentar_intern', models.TextField(blank=True, null=True)),
                ('kommentar_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ereignis',
            },
        ),
        migrations.CreateModel(
            name='EreignisTyp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255)),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('aatid', models.CharField(blank=True, max_length=255, null=True)),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
                ('lido_terminologie_link', models.CharField(blank=True, max_length=255, null=True)),
                ('wikidataid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ereignis_typ',
            },
        ),
        migrations.CreateModel(
            name='EreignisTypSynonyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ereignis_typ_id', models.BigIntegerField()),
                ('synonyme_string', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ereignis_typ_synonyme',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('file_uri', models.CharField(max_length=255)),
                ('original_file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('content_type', models.CharField(max_length=255)),
                ('upload_id', models.CharField(max_length=255, unique=True)),
                ('associated_property', models.CharField(max_length=255)),
                ('associated_entity', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'file_upload',
            },
        ),
        migrations.CreateModel(
            name='Hochschule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('signatur', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_de', models.CharField(max_length=255)),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
                ('wikidataid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'hochschule',
            },
        ),
        migrations.CreateModel(
            name='Informationstraeger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('beschreibung_en', models.CharField(blank=True, max_length=255, null=True)),
                ('kompilationstitel', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('measurements', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
                ('normdaten', models.CharField(blank=True, max_length=255, null=True)),
                ('kommentar_de', models.CharField(blank=True, max_length=255, null=True)),
                ('kompilations_reihennummer', models.CharField(blank=True, max_length=255, null=True)),
                ('beschreibung_de', models.CharField(blank=True, max_length=255, null=True)),
                ('erhaltungszustand_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('erhaltungszustand_de', models.CharField(blank=True, max_length=255, null=True)),
                ('externe_inventar_signaturnummern', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('provenienz', models.CharField(blank=True, max_length=255, null=True)),
                ('kommentar_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('interner_kommentar', models.CharField(blank=True, max_length=255, null=True)),
                ('kompilation', models.BigIntegerField(blank=True, null=True)),
                ('aatid', models.CharField(blank=True, max_length=255, null=True)),
                ('wikidataid', models.CharField(blank=True, max_length=255, null=True)),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
                ('pbcore_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'informationstraeger',
            },
        ),
        migrations.CreateModel(
            name='Informationstraegereigenschaft',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('wikidataid', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'informationstraegereigenschaft',
            },
        ),
        migrations.CreateModel(
            name='Inhaltswarnung',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('text_de', models.CharField(blank=True, max_length=255, null=True)),
                ('text_en', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inhaltswarnung',
            },
        ),
        migrations.CreateModel(
            name='Materialschlagwort',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('wikidata_item', models.CharField(max_length=255, unique=True)),
                ('description_de', models.TextField()),
                ('label_en', models.CharField(max_length=255)),
                ('label_de', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'materialschlagwort',
            },
        ),
        migrations.CreateModel(
            name='Nummernart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
                ('wikidataid', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nummernart',
            },
        ),
        migrations.CreateModel(
            name='ProjektAngegebeneNutzungsrechte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt_id', models.BigIntegerField(blank=True, null=True)),
                ('angegebene_nutzungsrechte', models.BigIntegerField(blank=True, null=True)),
                ('angegebene_nutzungsrechte_idx', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projekt_angegebene_nutzungsrechte',
            },
        ),
        migrations.CreateModel(
            name='ProjektArt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('wikidataid', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_de', models.CharField(max_length=255)),
                ('last_updated_by', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'projekt_art',
            },
        ),
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'registration_code',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('authority', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Sammlung',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('beschreibung_en', models.TextField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('sammlungs_art', models.CharField(max_length=255)),
                ('bezeichnung_de', models.CharField(max_length=255)),
                ('bezeichnung_en', models.CharField(max_length=255)),
                ('beschreibung_de', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sammlung',
            },
        ),
        migrations.CreateModel(
            name='Schlagwort',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('wikidata_item', models.CharField(max_length=255, unique=True)),
                ('description_de', models.TextField()),
                ('label_en', models.CharField(blank=True, max_length=255, null=True)),
                ('label_de', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField()),
                ('gnd_item', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'schlagwort',
            },
        ),
        migrations.CreateModel(
            name='Sprache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('name_en', models.CharField(max_length=255)),
                ('name_de', models.CharField(max_length=255)),
                ('last_updated_by', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('iso_639_2_b_code', models.CharField(max_length=255)),
                ('iso_639_1_code', models.CharField(max_length=255)),
                ('iso_639_2_t_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sprache',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('password_expired', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
                ('account_expired', models.BooleanField()),
                ('username', models.CharField(max_length=255, unique=True)),
                ('account_locked', models.BooleanField()),
                ('password', models.CharField(max_length=255)),
                ('enabled', models.BooleanField()),
                ('email', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Zeitpunkt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('monat', models.BigIntegerField(blank=True, null=True)),
                ('jahr', models.BigIntegerField()),
                ('tag', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zeitpunkt',
            },
        ),
        migrations.CreateModel(
            name='AkteurRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('art_der_relation', models.BigIntegerField()),
                ('akteur_relationen_idx', models.BigIntegerField(blank=True, null=True)),
                ('akteur1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.akteur')),
                ('akteur2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='akteurrelation_akteur2_set', to='metadata.akteur')),
            ],
            options={
                'db_table': 'akteur_relation',
            },
        ),
        migrations.CreateModel(
            name='DigitalesObjekt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('last_updated_by', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('derivat_kopie_nummer', models.CharField(blank=True, max_length=255, null=True)),
                ('dateipaket', models.BooleanField(blank=True, null=True)),
                ('medientyp', models.BigIntegerField()),
                ('erhaltungstyp', models.BigIntegerField(blank=True, null=True)),
                ('entstehungstyp', models.BigIntegerField()),
                ('created_by', models.CharField(max_length=255)),
                ('beschreibende_metadaten_teil_einer_serie', models.BooleanField(blank=True, null=True)),
                ('beschreibende_metadaten_date_updated_einlieferer', models.DateTimeField(blank=True, null=True)),
                ('beschreibende_metadaten_last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('beschreibende_metadaten_tonmischfassung', models.CharField(blank=True, max_length=255, null=True)),
                ('beschreibende_metadaten_systemvorraussetzungen', models.TextField(blank=True, null=True)),
                ('beschreibende_metadaten_id_beim_einlieferer', models.CharField(blank=True, max_length=255, null=True)),
                ('beschreibende_metadaten_bildbeschreibung_de', models.TextField(blank=True, null=True)),
                ('beschreibende_metadaten_inhalt_de', models.TextField(blank=True, null=True)),
                ('beschreibende_metadaten_inhalt_en', models.TextField(blank=True, null=True)),
                ('beschreibende_metadaten_kommentar_de', models.TextField(blank=True, null=True)),
                ('beschreibende_metadaten_eigenschaften_de', models.TextField(blank=True, null=True)),
                ('beschreibende_metadaten_eq', models.TextField(blank=True, null=True)),
                ('beschreibende_metadaten_kommentar_intern', models.TextField(blank=True, null=True)),
                ('beschreibende_metadaten_eigenschaften_en', models.TextField(blank=True, null=True)),
                ('beschreibende_metadaten_date_created_einlieferer', models.DateTimeField(blank=True, null=True)),
                ('beschreibende_metadaten_schleife', models.BooleanField(blank=True, null=True)),
                ('beschreibende_metadaten_projektkompilation', models.BigIntegerField(blank=True, null=True)),
                ('beschreibende_metadaten_kommentar_en', models.TextField(blank=True, null=True)),
                ('beschreibende_metadaten_tonformat', models.CharField(blank=True, max_length=255, null=True)),
                ('beschreibende_metadaten_bildbeschreibung_en', models.TextField(blank=True, null=True)),
                ('technische_metadaten_droidpuid', models.CharField(blank=True, max_length=255, null=True)),
                ('technische_metadaten_exif_toolxml', models.TextField(blank=True, null=True)),
                ('technische_metadaten_jhovedateistatus', models.CharField(blank=True, max_length=255, null=True)),
                ('technische_metadaten_jhovexml', models.TextField(blank=True, null=True)),
                ('technische_metadaten_droidxml', models.TextField(blank=True, null=True)),
                ('technische_metadaten_duration', models.BigIntegerField(blank=True, null=True)),
                ('technische_metadaten_dateifamilie', models.CharField(blank=True, max_length=255, null=True)),
                ('technische_metadaten_dateityp_kurz', models.CharField(blank=True, max_length=255, null=True)),
                ('technische_metadaten_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('technische_metadaten_media_infoxml', models.TextField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField()),
                ('use_preview', models.BooleanField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('lizenzstatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.digitalesobjektlizenz')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.fileupload')),
                ('beschreibende_metadaten_einlieferndehs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.hochschule')),
                ('beschreibende_metadaten_sprache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='digitalesobjekt_beschreibende_metadaten_sprache_set', to='metadata.sprache')),
                ('beschreibende_metadaten_sprachfassung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='digitalesobjekt_beschreibende_metadaten_sprachfassung_set', to='metadata.sprache')),
                ('beschreibende_metadaten_untertitelsprache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.sprache')),
            ],
            options={
                'db_table': 'digitales_objekt',
            },
        ),
        migrations.CreateModel(
            name='EquipmentSoftware',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('beschreibung_en', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('normdaten', models.CharField(blank=True, max_length=255, null=True)),
                ('hersteller', models.CharField(blank=True, max_length=255, null=True)),
                ('beschreibung_de', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255)),
                ('wikidataid', models.CharField(blank=True, max_length=255, null=True)),
                ('equipmentart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.equipmentart')),
            ],
            options={
                'db_table': 'equipment_software',
            },
        ),
        migrations.CreateModel(
            name='EreignisAkteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.akteur')),
                ('ereignis_akteure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignis')),
            ],
            options={
                'db_table': 'ereignis_akteur',
            },
        ),
        migrations.CreateModel(
            name='EreignisDigitalesObjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digitales_objekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.digitalesobjekt')),
                ('ereignis_digitale_objekte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignis')),
            ],
            options={
                'db_table': 'ereignis_digitales_objekt',
            },
        ),
        migrations.CreateModel(
            name='EreignisEigenschaftswert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('wert', models.CharField(max_length=255)),
                ('ereignis_eigenschaften_idx', models.BigIntegerField(blank=True, null=True)),
                ('eigenschaft', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.eigenschaft')),
                ('ereignis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignis')),
            ],
            options={
                'db_table': 'ereignis_eigenschaftswert',
            },
        ),
        migrations.CreateModel(
            name='EreignisEquipmentSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.equipmentsoftware')),
                ('ereignis_equipment_software', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignis')),
            ],
            options={
                'db_table': 'ereignis_equipment_software',
            },
        ),
        migrations.CreateModel(
            name='EreignisRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('art_der_relation', models.BigIntegerField()),
                ('ereignis_relationen_idx', models.BigIntegerField(blank=True, null=True)),
                ('ereignis1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ereignisrelation_ereignis1_set', to='metadata.ereignis')),
                ('ereignis2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignis')),
            ],
            options={
                'db_table': 'ereignis_relation',
            },
        ),
        migrations.AddField(
            model_name='ereignis',
            name='ereignis_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignistyp'),
        ),
        migrations.CreateModel(
            name='BestehenderLizenzvertrag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('lizenz_status', models.CharField(blank=True, max_length=255, null=True)),
                ('vertrags_text_de', models.CharField(blank=True, max_length=255, null=True)),
                ('bezeichnung_de', models.CharField(max_length=255)),
                ('bezeichnung_en', models.CharField(blank=True, max_length=255, null=True)),
                ('anzeige_status', models.CharField(blank=True, max_length=255, null=True)),
                ('vertrags_text_en', models.CharField(blank=True, max_length=255, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.fileupload')),
                ('hochschule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.hochschule')),
            ],
            options={
                'db_table': 'bestehender_lizenzvertrag',
            },
        ),
        migrations.CreateModel(
            name='EreignisInformationstraeger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ereignis_informationstraeger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignis')),
                ('informationstraeger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraeger')),
            ],
            options={
                'db_table': 'ereignis_informationstraeger',
            },
        ),
        migrations.CreateModel(
            name='InformationstraegerAkteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.akteur')),
                ('informationstraeger_besitzer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraeger')),
                ('informationstraeger_eigentuemer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='informationstraegerakteur_informationstraeger_eigentuemer_set', to='metadata.informationstraeger')),
            ],
            options={
                'db_table': 'informationstraeger_akteur',
            },
        ),
        migrations.CreateModel(
            name='InformationstraegerBesitzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.akteur')),
                ('informationstraeger_besitzer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraeger')),
            ],
            options={
                'db_table': 'informationstraeger_besitzer',
            },
        ),
        migrations.CreateModel(
            name='InformationstraegerEigenschaftswert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('wert', models.CharField(max_length=255)),
                ('eigenschaft', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.eigenschaft')),
                ('informationstraeger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraeger')),
            ],
            options={
                'db_table': 'informationstraeger_eigenschaftswert',
            },
        ),
        migrations.CreateModel(
            name='InformationstraegerEigentuemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.akteur')),
                ('informationstraeger_eigentuemer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraeger')),
            ],
            options={
                'db_table': 'informationstraeger_eigentuemer',
            },
        ),
        migrations.CreateModel(
            name='Informationstraegertyp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('aatid', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
                ('wikidataid', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255)),
                ('pbcore_link', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraegertyp')),
            ],
            options={
                'db_table': 'informationstraegertyp',
            },
        ),
        migrations.AddField(
            model_name='informationstraeger',
            name='informationstraegertyp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraegertyp'),
        ),
        migrations.CreateModel(
            name='InformationstraegertypSynonyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonyme_string', models.CharField(blank=True, max_length=255, null=True)),
                ('informationstraegertyp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraegertyp')),
            ],
            options={
                'db_table': 'informationstraegertyp_synonyme',
            },
        ),
        migrations.CreateModel(
            name='MaterialschlagwortSynonymDe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym_de_string', models.CharField(blank=True, max_length=255, null=True)),
                ('materialschlagwort', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.materialschlagwort')),
            ],
            options={
                'db_table': 'materialschlagwort_synonym_de',
            },
        ),
        migrations.CreateModel(
            name='MaterialschlagwortSynonymEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym_en_string', models.CharField(blank=True, max_length=255, null=True)),
                ('materialschlagwort', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.materialschlagwort')),
            ],
            options={
                'db_table': 'materialschlagwort_synonym_en',
            },
        ),
        migrations.CreateModel(
            name='Organisationseinheit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('beschreibung_en', models.TextField(blank=True, null=True)),
                ('beschreibung_de', models.TextField(blank=True, null=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_de', models.CharField(max_length=255)),
                ('hochschule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.hochschule')),
            ],
            options={
                'db_table': 'organisationseinheit',
            },
        ),
        migrations.AddField(
            model_name='akteur',
            name='einlieferer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.organisationseinheit'),
        ),
        migrations.CreateModel(
            name='Ort',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('wikidata_item', models.CharField(max_length=255)),
                ('kategorie', models.BigIntegerField()),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('viafid', models.CharField(blank=True, max_length=255, null=True)),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ort')),
            ],
            options={
                'db_table': 'ort',
            },
        ),
        migrations.AddField(
            model_name='informationstraeger',
            name='aufbewahrungsort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ort'),
        ),
        migrations.CreateModel(
            name='EreignisOrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ereignis_orte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignis')),
                ('ort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ort')),
            ],
            options={
                'db_table': 'ereignis_ort',
            },
        ),
        migrations.CreateModel(
            name='AkteurOrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akteur_wirkungsorte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.akteur')),
                ('ort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ort')),
            ],
            options={
                'db_table': 'akteur_ort',
            },
        ),
        migrations.AddField(
            model_name='akteur',
            name='aufloesungort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ort'),
        ),
        migrations.AddField(
            model_name='akteur',
            name='geburtsort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='akteur_geburtsort_set', to='metadata.ort'),
        ),
        migrations.AddField(
            model_name='akteur',
            name='gruendungsort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='akteur_gruendungsort_set', to='metadata.ort'),
        ),
        migrations.AddField(
            model_name='akteur',
            name='sterbeort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='akteur_sterbeort_set', to='metadata.ort'),
        ),
        migrations.CreateModel(
            name='PhysischesObjekt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('externe_inventar_signaturnummern', models.CharField(blank=True, max_length=255, null=True)),
                ('beschreibung_de', models.TextField(blank=True, null=True)),
                ('beschreibung_en', models.TextField(blank=True, null=True)),
                ('kommentar_de', models.TextField(blank=True, null=True)),
                ('kommentar_en', models.TextField(blank=True, null=True)),
                ('kommentar_intern', models.TextField(blank=True, null=True)),
                ('erhaltungszustand_de', models.CharField(blank=True, max_length=255, null=True)),
                ('erhaltungszustand_en', models.CharField(blank=True, max_length=255, null=True)),
                ('measurements', models.CharField(blank=True, max_length=255, null=True)),
                ('provenienz', models.TextField(blank=True, null=True)),
                ('persistenter_identifikator', models.CharField(blank=True, max_length=255, null=True)),
                ('kommentar_technik_de', models.TextField(blank=True, null=True)),
                ('kommentar_technik_en', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
                ('aufbewahrungsort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ort')),
            ],
            options={
                'db_table': 'physisches_objekt',
            },
        ),
        migrations.CreateModel(
            name='EreignisPhysischesObjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ereignis_physische_objekte_id', models.BigIntegerField()),
                ('physisches_objekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.physischesobjekt')),
            ],
            options={
                'db_table': 'ereignis_physisches_objekt',
            },
        ),
        migrations.CreateModel(
            name='PhysischesObjektAkteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.akteur')),
                ('physisches_objekt_besitzer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.physischesobjekt')),
                ('physisches_objekt_eigentuemer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='physischesobjektakteur_physisches_objekt_eigentuemer_set', to='metadata.physischesobjekt')),
            ],
            options={
                'db_table': 'physisches_objekt_akteur',
            },
        ),
        migrations.CreateModel(
            name='PhysischesObjektBesitzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.akteur')),
                ('physisches_objekt_besitzer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.physischesobjekt')),
            ],
            options={
                'db_table': 'physisches_objekt_besitzer',
            },
        ),
        migrations.CreateModel(
            name='PhysischesObjektEigentuemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.akteur')),
                ('physisches_objekt_eigentuemer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.physischesobjekt')),
            ],
            options={
                'db_table': 'physisches_objekt_eigentuemer',
            },
        ),
        migrations.CreateModel(
            name='ProduktId',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('wert', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('informationstraeger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraeger')),
                ('nummernart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.nummernart')),
            ],
            options={
                'db_table': 'produkt_id',
            },
        ),
        migrations.CreateModel(
            name='PhysischesObjektProduktId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physisches_objekt_produkt_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.physischesobjekt')),
                ('produkt_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.produktid')),
            ],
            options={
                'db_table': 'physisches_objekt_produkt_id',
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('normdatei', models.TextField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('signatur', models.CharField(blank=True, max_length=255, null=True)),
                ('rechtsstatus', models.BigIntegerField()),
                ('letzte_modifikation', models.DateTimeField(blank=True, null=True)),
                ('kommentar_de', models.TextField(blank=True, null=True)),
                ('art_lizenzvertrag', models.BigIntegerField(blank=True, null=True)),
                ('kommentar_en', models.TextField(blank=True, null=True)),
                ('tonart', models.CharField(blank=True, max_length=255, null=True)),
                ('sonderregelung', models.BigIntegerField(blank=True, null=True)),
                ('externe_projekt_webseite', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('signatur_einlieferer', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BigIntegerField()),
                ('verzeichnisnummern', models.CharField(blank=True, max_length=255, null=True)),
                ('dauer', models.CharField(blank=True, max_length=255, null=True)),
                ('kommentar_intern', models.TextField(blank=True, null=True)),
                ('erstellungs_datum_einlieferer', models.DateTimeField(blank=True, null=True)),
                ('wikidataid', models.CharField(blank=True, max_length=255, null=True)),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
                ('bestehender_lizenzvertrag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.bestehenderlizenzvertrag')),
                ('dateiabfrage_dokument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.fileupload')),
                ('dokumentation_lizenzvertrag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projekt_dokumentation_lizenzvertrag_set', to='metadata.fileupload')),
                ('hochschule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.hochschule')),
                ('neuer_lizenzvertrag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projekt_neuer_lizenzvertrag_set', to='metadata.fileupload')),
            ],
            options={
                'db_table': 'projekt',
            },
        ),
        migrations.CreateModel(
            name='ProjektEigenschaftswert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('wert', models.CharField(max_length=255)),
                ('projekt_eigenschaften_idx', models.BigIntegerField(blank=True, null=True)),
                ('eigenschaft', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.eigenschaft')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projekt')),
            ],
            options={
                'db_table': 'projekt_eigenschaftswert',
            },
        ),
        migrations.CreateModel(
            name='ProjektEreignis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ereignis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignis')),
                ('projekt_ereignisse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projekt')),
            ],
            options={
                'db_table': 'projekt_ereignis',
            },
        ),
        migrations.CreateModel(
            name='ProjektFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt_weitere_rechtsdokumente_id', models.BigIntegerField(blank=True, null=True)),
                ('weitere_rechtsdokumente_idx', models.BigIntegerField(blank=True, null=True)),
                ('file_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.fileupload')),
            ],
            options={
                'db_table': 'projekt_file_upload',
            },
        ),
        migrations.CreateModel(
            name='ProjektInhaltswarnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt_id', models.BigIntegerField()),
                ('inhaltswarnungen_idx', models.BigIntegerField(blank=True, null=True)),
                ('inhaltswarnung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.inhaltswarnung')),
            ],
            options={
                'db_table': 'projekt_inhaltswarnung',
            },
        ),
        migrations.CreateModel(
            name='ProjektKategorie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255)),
                ('last_updated_by', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('aatid', models.CharField(blank=True, max_length=255, null=True)),
                ('wikidataid', models.CharField(blank=True, max_length=255, null=True)),
                ('gndid', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projektkategorie')),
            ],
            options={
                'db_table': 'projekt_kategorie',
            },
        ),
        migrations.CreateModel(
            name='ProjektKategorieSynonyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonyme_string', models.CharField(blank=True, max_length=255, null=True)),
                ('projekt_kategorie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projektkategorie')),
            ],
            options={
                'db_table': 'projekt_kategorie_synonyme',
            },
        ),
        migrations.CreateModel(
            name='ProjektOrganisationseinheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisationseinheit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.organisationseinheit')),
                ('projekt_organisationseinheit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projekt')),
            ],
            options={
                'db_table': 'projekt_organisationseinheit',
            },
        ),
        migrations.CreateModel(
            name='ProjektProjektArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt_art', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projektart')),
                ('projekt_projekt_art', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projekt')),
            ],
            options={
                'db_table': 'projekt_projekt_art',
            },
        ),
        migrations.CreateModel(
            name='ProjektProjektKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorii', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projekt')),
                ('projekt_kategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projektkategorie')),
            ],
            options={
                'db_table': 'projekt_projekt_kategorie',
            },
        ),
        migrations.CreateModel(
            name='ProjektRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('art_der_relation', models.BigIntegerField()),
                ('projekt_relationen_idx', models.BigIntegerField(blank=True, null=True)),
                ('projekt1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projektrelation_projekt1_set', to='metadata.projekt')),
                ('projekt2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projekt')),
            ],
            options={
                'db_table': 'projekt_relation',
            },
        ),
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255)),
                ('gndidg', models.CharField(blank=True, max_length=255, null=True)),
                ('aatid', models.CharField(blank=True, max_length=255, null=True)),
                ('gndidm', models.CharField(blank=True, max_length=255, null=True)),
                ('wikidataid', models.CharField(max_length=255)),
                ('gndidw', models.CharField(blank=True, max_length=255, null=True)),
                ('preselect_leistungsschutzrechte', models.BooleanField()),
                ('preselect_urheber', models.BooleanField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.rolle')),
            ],
            options={
                'db_table': 'rolle',
            },
        ),
        migrations.CreateModel(
            name='EreignisRolle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('urheber', models.BooleanField(blank=True, null=True)),
                ('leistungsschutzrechte', models.BooleanField(blank=True, null=True)),
                ('ereignis_rollen_idx', models.BigIntegerField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('ungesicherte_zuschreibung', models.BooleanField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.BigIntegerField()),
                ('akteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.akteur')),
                ('ereignis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignis')),
                ('rolle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.rolle')),
            ],
            options={
                'db_table': 'ereignis_rolle',
            },
        ),
        migrations.CreateModel(
            name='AkteurRolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akteur_berufe_taetigkeiten', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.akteur')),
                ('rolle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.rolle')),
            ],
            options={
                'db_table': 'akteur_rolle',
            },
        ),
        migrations.CreateModel(
            name='RolleRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('last_updated_by', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('akteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.akteur')),
                ('ereignis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignis')),
            ],
            options={
                'db_table': 'rolle_relation',
            },
        ),
        migrations.CreateModel(
            name='RolleRelationRolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.rolle')),
                ('rolle_relation_rollen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.rollerelation')),
            ],
            options={
                'db_table': 'rolle_relation_rolle',
            },
        ),
        migrations.CreateModel(
            name='RolleSynonyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonyme_string', models.CharField(blank=True, max_length=255, null=True)),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.rolle')),
            ],
            options={
                'db_table': 'rolle_synonyme',
            },
        ),
        migrations.CreateModel(
            name='SammlungVerknuepftesEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.equipmentsoftware')),
                ('sammlung', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.sammlung')),
            ],
            options={
                'db_table': 'sammlung_verknuepftes_equipment',
            },
        ),
        migrations.CreateModel(
            name='ProjektSchlagworte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt_schlagworte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projekt')),
                ('schlagwort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.schlagwort')),
            ],
            options={
                'db_table': 'projekt_schlagworte',
            },
        ),
        migrations.CreateModel(
            name='PhysischesObjektTechnikschlagworte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physisches_objekt_technikschlagworte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.physischesobjekt')),
                ('schlagwort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.schlagwort')),
            ],
            options={
                'db_table': 'physisches_objekt_technikschlagworte',
            },
        ),
        migrations.CreateModel(
            name='PhysischesObjektSchlagworte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physisches_objekt_schlagworte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.physischesobjekt')),
                ('schlagwort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.schlagwort')),
            ],
            options={
                'db_table': 'physisches_objekt_schlagworte',
            },
        ),
        migrations.CreateModel(
            name='PhysischesObjektMaterialschlagworte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physisches_objekt_materialschlagworte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.physischesobjekt')),
                ('schlagwort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.schlagwort')),
            ],
            options={
                'db_table': 'physisches_objekt_materialschlagworte',
            },
        ),
        migrations.CreateModel(
            name='InformationstraegerSchlagwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informationstraeger_materialschlagwort', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraeger')),
                ('schlagwort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.schlagwort')),
            ],
            options={
                'db_table': 'informationstraeger_schlagwort',
            },
        ),
        migrations.CreateModel(
            name='DigitalesObjektSchlagwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digitales_objekt_objekttypen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.digitalesobjekt')),
                ('schlagwort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.schlagwort')),
            ],
            options={
                'db_table': 'digitales_objekt_schlagwort',
            },
        ),
        migrations.CreateModel(
            name='SchlagwortSynonymeDe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonyme_de_string', models.CharField(blank=True, max_length=255, null=True)),
                ('schlagwort', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.schlagwort')),
            ],
            options={
                'db_table': 'schlagwort_synonyme_de',
            },
        ),
        migrations.CreateModel(
            name='SchlagwortSynonymeEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonyme_en_string', models.CharField(blank=True, max_length=255, null=True)),
                ('schlagwort', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.schlagwort')),
            ],
            options={
                'db_table': 'schlagwort_synonyme_en',
            },
        ),
        migrations.CreateModel(
            name='ProjektBeschreibung',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('rang', models.BigIntegerField()),
                ('beschreibung', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projekt')),
                ('sprache', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.sprache')),
            ],
            options={
                'db_table': 'projekt_beschreibung',
            },
        ),
        migrations.CreateModel(
            name='InformationstraegerUntertitelsprachen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informationstraeger_untertitelsprachen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraeger')),
                ('sprache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.sprache')),
            ],
            options={
                'db_table': 'informationstraeger_untertitelsprachen',
            },
        ),
        migrations.CreateModel(
            name='InformationstraegerSprachfassungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informationstraeger_sprachfassungen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraeger')),
                ('sprache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.sprache')),
            ],
            options={
                'db_table': 'informationstraeger_sprachfassungen',
            },
        ),
        migrations.CreateModel(
            name='InformationstraegerSprache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informationstraeger_originalsprachen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='informationstraegersprache_informationstraeger_originalsprachen_set', to='metadata.informationstraeger')),
                ('informationstraeger_sprachfassungen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='informationstraegersprache_informationstraeger_sprachfassungen_set', to='metadata.informationstraeger')),
                ('informationstraeger_untertitelsprachen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraeger')),
                ('sprache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.sprache')),
            ],
            options={
                'db_table': 'informationstraeger_sprache',
            },
        ),
        migrations.CreateModel(
            name='InformationstraegerOriginalsprachen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informationstraeger_originalsprachen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraeger')),
                ('sprache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.sprache')),
            ],
            options={
                'db_table': 'informationstraeger_originalsprachen',
            },
        ),
        migrations.CreateModel(
            name='EreignisBeschreibung',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('beschreibung', models.TextField()),
                ('wertigkeit', models.BigIntegerField()),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('ereignis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignis')),
                ('sprache', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.sprache')),
            ],
            options={
                'db_table': 'ereignis_beschreibung',
            },
        ),
        migrations.CreateModel(
            name='Titel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('untertitel', models.CharField(blank=True, max_length=255, null=True)),
                ('titel', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('rang', models.BigIntegerField()),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projekt')),
                ('sprache_titel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.sprache')),
                ('sprache_untertitel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='titel_sprache_untertitel_set', to='metadata.sprache')),
            ],
            options={
                'db_table': 'titel',
            },
        ),
        migrations.AddField(
            model_name='projekt',
            name='bevorzugter_titel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preferred_for_projects', to='metadata.titel'),
        ),
        migrations.CreateModel(
            name='Tooltip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('tt_text_en', models.CharField(blank=True, max_length=1024, null=True)),
                ('tt_text_de', models.CharField(blank=True, max_length=1024, null=True)),
                ('view', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tooltip',
                'unique_together': {('view', 'field')},
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('anrede', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('vorname', models.CharField(max_length=255)),
                ('newsletter', models.BooleanField(blank=True, null=True)),
                ('ort', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
                ('nachname', models.CharField(max_length=255)),
                ('max_rows', models.BigIntegerField(blank=True, null=True)),
                ('color_mode', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.fileupload')),
                ('hochschule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.hochschule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.user')),
            ],
            options={
                'db_table': 'user_detail',
            },
        ),
        migrations.CreateModel(
            name='SammlungVerknuepfteDigitaleObjekte',
            fields=[
                ('sammlung', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='metadata.sammlung')),
                ('digitales_objekt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.digitalesobjekt')),
            ],
            options={
                'db_table': 'sammlung_verknuepfte_digitale_objekte',
                'unique_together': {('sammlung', 'digitales_objekt')},
            },
        ),
        migrations.CreateModel(
            name='SammlungVerknuepfteEreignisse',
            fields=[
                ('sammlung', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='metadata.sammlung')),
                ('ereignis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.ereignis')),
            ],
            options={
                'db_table': 'sammlung_verknuepfte_ereignisse',
                'unique_together': {('sammlung', 'ereignis')},
            },
        ),
        migrations.CreateModel(
            name='SammlungVerknuepfteInformationstraeger',
            fields=[
                ('sammlung', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='metadata.sammlung')),
                ('informationstraeger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.informationstraeger')),
            ],
            options={
                'db_table': 'sammlung_verknuepfte_informationstraeger',
                'unique_together': {('sammlung', 'informationstraeger')},
            },
        ),
        migrations.CreateModel(
            name='SammlungVerknuepftePhysischeObjekte',
            fields=[
                ('sammlung', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='metadata.sammlung')),
                ('physisches_objekt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.physischesobjekt')),
            ],
            options={
                'db_table': 'sammlung_verknuepfte_physische_objekte',
                'unique_together': {('sammlung', 'physisches_objekt')},
            },
        ),
        migrations.CreateModel(
            name='SammlungVerknuepfteProjekte',
            fields=[
                ('sammlung', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='metadata.sammlung')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.projekt')),
            ],
            options={
                'db_table': 'sammlung_verknuepfte_projekte',
                'unique_together': {('sammlung', 'projekt')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='metadata.user')),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.role')),
            ],
            options={
                'db_table': 'user_role',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
