# Generated by Django 5.0.11 on 2025-07-23 09:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0000_enable_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIDOCClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_primitive', models.BooleanField(default=False, help_text='If True, this class represents a primitive value type (E59, E60, etc.)')),
            ],
            options={
                'verbose_name': 'CIDOC Class',
                'verbose_name_plural': 'CIDOC Classes',
            },
        ),
        migrations.CreateModel(
            name='CIDOCProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_functional', models.BooleanField(default=False, help_text='Property can have at most one value')),
                ('is_symmetric', models.BooleanField(default=False, help_text='If A relates to B, then B relates to A')),
                ('is_transitive', models.BooleanField(default=False, help_text='If A relates to B and B to C, then A relates to C')),
            ],
            options={
                'verbose_name': 'CIDOC Property',
                'verbose_name_plural': 'CIDOC Properties',
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this mapping does')),
                ('organization_id', models.CharField(db_index=True, max_length=255)),
                ('source_datasets', models.JSONField(default=list, help_text='DEPRECATED: List of datasets - now computed from mapping_config')),
                ('mapping_config', models.JSONField(default=dict, help_text='Flexible mapping configuration interpreted by GUI')),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('active', 'Active')], default='draft', max_length=20)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('execution_stats', models.JSONField(default=dict, help_text='Statistics from last execution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uri', models.URLField(blank=True, help_text='Uniform Resource Identifier for this resource', max_length=512, null=True, unique=True)),
                ('resource_type', models.CharField(choices=[('IRI', 'IRI Identified Resource'), ('CLASS', 'Class'), ('PROPERTY', 'Property'), ('LITERAL', 'Literal')], default='IRI', help_text='Type of the resource (IRI, Class, Property, or Literal)', max_length=10)),
                ('public_access_level', models.CharField(choices=[('private', 'Private - Organization only'), ('restricted', 'Restricted - Authenticated users only'), ('public', 'Public - Catalog display allowed')], default='private', help_text='Level of public access for this resource', max_length=20)),
                ('is_public_approved', models.BooleanField(default=False, help_text='Has this resource been approved for public catalog display?')),
                ('public_approved_at', models.DateTimeField(blank=True, help_text='When this resource was approved for public access', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this resource is visible to users from other organizations')),
                ('is_externally_linked', models.BooleanField(default=False, help_text='Whether this resource is referenced by users from other organizations')),
                ('name', models.TextField(blank=True, help_text='Name of the column, property, or context this resource represents', max_length=255, null=True)),
                ('value', models.TextField(blank=True, help_text='Value of this resource (literal value or descriptive value for IRIs)', null=True)),
                ('value_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of the value field for efficient uniqueness checking', max_length=64, null=True)),
                ('is_placeholder', models.BooleanField(default=False, help_text="Indicates if this is a placeholder resource created during cross-reference that hasn't been fully imported yet")),
                ('datatype', models.CharField(blank=True, help_text='Datatype URI for literal values (e.g., xsd:string, xsd:integer)', max_length=255, null=True)),
                ('language', models.CharField(blank=True, help_text="Language tag for language-tagged string literals (e.g., 'en', 'fr')", max_length=10, null=True)),
            ],
            options={
                'permissions': [('share_resource', 'Can share resource with others'), ('can_approve_public_access', 'Can approve resources for public access')],
            },
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_derived', models.BooleanField(db_index=True, default=False, help_text='True if system-generated, not from source archive')),
            ],
        ),
    ]
