# Generated by Django 5.0.11 on 2025-05-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_placeholder',
            field=models.BooleanField(default=False, help_text="Indicates if this is a placeholder resource created during cross-reference that hasn't been fully imported yet"),
        ),
    ]
