# Generated by Django 5.0.11 on 2025-07-23 09:24

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cidocclass',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cidocclass',
            name='parent_classes',
            field=models.ManyToManyField(blank=True, related_name='child_classes', to='metadata.cidocclass'),
        ),
        migrations.AddField(
            model_name='cidocclass',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cidocproperty',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cidocproperty',
            name='domain_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_properties', to='metadata.cidocclass'),
        ),
        migrations.AddField(
            model_name='cidocproperty',
            name='inverse_property',
            field=models.ForeignKey(blank=True, help_text='The inverse property (e.g., P1i for P1)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inverse_of', to='metadata.cidocproperty'),
        ),
        migrations.AddField(
            model_name='cidocproperty',
            name='parent_properties',
            field=models.ManyToManyField(blank=True, related_name='child_properties', to='metadata.cidocproperty'),
        ),
        migrations.AddField(
            model_name='cidocproperty',
            name='range_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_properties', to='metadata.cidocclass'),
        ),
        migrations.AddField(
            model_name='cidocproperty',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapping',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapping',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this resource belongs to (for permissions)', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddField(
            model_name='resource',
            name='public_approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this resource for public access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_approved_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triple',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triple',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_triples', to='metadata.resource'),
        ),
        migrations.AddField(
            model_name='triple',
            name='predicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicate_triples', to='metadata.resource'),
        ),
        migrations.AddField(
            model_name='triple',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this triple. Null for derived triples.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization'),
        ),
        migrations.AddField(
            model_name='triple',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_triples', to='metadata.resource'),
        ),
        migrations.AddField(
            model_name='triple',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['organization_id', 'validation_status'], name='metadata_ma_organiz_f75d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['created_by', 'validation_status'], name='metadata_ma_created_94b7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['uri'], name='uri_pattern_idx', opclasses=['varchar_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['organization'], name='metadata_re_organiz_7e10dc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['public_access_level', 'is_public_approved'], name='metadata_re_public__fb19d0_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=django.contrib.postgres.indexes.GinIndex(condition=models.Q(('resource_type', 'LITERAL')), fields=['value'], name='resource_value_search_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('resource_type', 'LITERAL'), ('value__isnull', False)), models.Q(models.Q(('resource_type', 'LITERAL'), _negated=True), ('uri__isnull', False)), _connector='OR'), name='resource_type_consistency'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(condition=models.Q(('resource_type', 'LITERAL')), fields=('value_hash', 'language', 'datatype', 'name'), name='unique_literal_value_hash'),
        ),
        migrations.AddIndex(
            model_name='triple',
            index=models.Index(fields=['subject', 'predicate'], name='metadata_tr_subject_ef08e4_idx'),
        ),
        migrations.AddIndex(
            model_name='triple',
            index=models.Index(fields=['object'], name='metadata_tr_object__7d1258_idx'),
        ),
        migrations.AddIndex(
            model_name='triple',
            index=models.Index(fields=['object', 'predicate'], name='metadata_tr_object__230fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='triple',
            index=models.Index(fields=['predicate'], name='metadata_tr_predica_1fa8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='triple',
            index=models.Index(fields=['source'], name='metadata_tr_source__4cd036_idx'),
        ),
        migrations.AddIndex(
            model_name='triple',
            index=models.Index(fields=['is_derived'], name='metadata_tr_is_deri_e084f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='triple',
            constraint=models.UniqueConstraint(fields=('subject', 'predicate', 'object', 'source'), name='unique_archival_triple'),
        ),
        migrations.AddConstraint(
            model_name='triple',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', True)), fields=('subject', 'predicate', 'object'), name='unique_derived_triple'),
        ),
    ]
