# Generated by Django 5.0.11 on 2025-07-23 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resource',
            name='unique_literal_value_hash',
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(condition=models.Q(('resource_type', 'LITERAL')), fields=('value_hash', 'language', 'datatype'), name='unique_literal_value_hash'),
        ),
    ]
