# Generated by Django 5.0.11 on 2025-05-22 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_resource_is_placeholder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(condition=models.Q(('resource_type', 'LITERAL')), fields=('literal_value', 'literal_language', 'literal_datatype'), name='unique_literal_value'),
        ),
    ]
