# Generated by Django 5.0.4 on 2025-07-25 08:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('metadata', '0003_remove_resource_unique_literal_value_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarmonizationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_property_pattern', models.CharField(help_text='Regex or exact match pattern for source properties', max_length=512)),
                ('catalog_property_uri', models.URLField(help_text='URI of the catalog-level property', max_length=512)),
                ('catalog_property_label', models.CharField(help_text='Human-readable label for the catalog property', max_length=255)),
                ('mapping_type', models.CharField(choices=[('exact', 'Exact Match'), ('close', 'Close Match'), ('broad', 'Broader Match'), ('narrow', 'Narrower Match')], default='exact', help_text='Type of semantic mapping', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority wins in conflicts')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this rule')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('source_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harmonization_rules', to='users.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_harmonization_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metadata_harmonization_rule',
                'ordering': ['-priority', 'catalog_property_label'],
                'indexes': [models.Index(fields=['source_organization', 'is_active'], name='metadata_ha_source__a3b5d2_idx'), models.Index(fields=['catalog_property_uri'], name='metadata_ha_catalog_e25fda_idx')],
                'unique_together': {('source_organization', 'source_property_pattern', 'catalog_property_uri')},
            },
        ),
        migrations.CreateModel(
            name='HarmonizationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resources_processed', models.IntegerField(default=0)),
                ('triples_created', models.IntegerField(default=0)),
                ('conflicts_resolved', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('execution_mode', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('triggered', 'Triggered by Import')], default='manual', max_length=20)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organizations', models.ManyToManyField(related_name='harmonization_executions', to='users.organization')),
                ('rules_applied', models.ManyToManyField(related_name='executions', to='metadata.harmonizationrule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metadata_harmonization_execution',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='metadata_ha_status_fb96f1_idx'), models.Index(fields=['completed_at'], name='metadata_ha_complet_d5848f_idx')],
            },
        ),
        migrations.CreateModel(
            name='HarmonizationConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_resource_uri', models.URLField(max_length=512)),
                ('resolution', models.CharField(choices=[('priority', 'Resolved by Priority'), ('manual', 'Manual Override'), ('skipped', 'Skipped'), ('pending', 'Pending Review')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('conflicting_rules', models.ManyToManyField(related_name='conflicts', to='metadata.harmonizationrule')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='metadata.harmonizationexecution')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('selected_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_conflicts', to='metadata.harmonizationrule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metadata_harmonization_conflict',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['execution', 'resolution'], name='metadata_ha_executi_c14502_idx'), models.Index(fields=['source_resource_uri'], name='metadata_ha_source__0b3fcc_idx')],
            },
        ),
    ]