# Generated by Django 5.0.11 on 2025-05-23 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_resource_unique_literal_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resource',
            name='resource_type_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='resource',
            name='unique_literal_value',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='literal_datatype',
            new_name='datatype',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='literal_language',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='literal_value',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='source_field',
        ),
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.TextField(blank=True, help_text='Name of the column, property, or context this resource represents', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='value',
            field=models.TextField(blank=True, help_text='Value of this resource (literal value or descriptive value for IRIs)', null=True),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['value'], name='value_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['source', 'name'], name='source_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('resource_type', 'LITERAL'), ('value__isnull', False)), models.Q(models.Q(('resource_type', 'LITERAL'), _negated=True), ('uri__isnull', False)), _connector='OR'), name='resource_type_consistency'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(condition=models.Q(('resource_type', 'LITERAL')), fields=('value', 'language', 'datatype', 'source', 'name'), name='unique_literal_value'),
        ),
        migrations.AddConstraint(
            model_name='triple',
            constraint=models.UniqueConstraint(fields=('subject', 'predicate', 'object'), name='unique_triple'),
        ),
    ]
