# Generated by Django 5.0.11 on 2025-06-06 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_remove_resource_resource_type_consistency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['source', 'uri'], name='metadata_re_source_7b5c62_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['source', 'resource_type'], name='metadata_re_source_d25385_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['uri'], name='uri_pattern_idx', opclasses=['varchar_pattern_ops']),
        ),
    ]
