# Generated by Django 5.0.11 on 2025-06-11 17:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_resource_metadata_re_source_7b5c62_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('mapping_type', models.CharField(choices=[('entity', 'Entity Mapping'), ('lookup', 'Lookup Mapping'), ('vocabulary', 'Vocabulary Mapping'), ('junction', 'Junction Mapping')], max_length=20)),
                ('scope', models.CharField(default='multi_dataset', max_length=20)),
                ('organization_id', models.CharField(db_index=True, max_length=255)),
                ('source_dataset', models.CharField(help_text='Primary dataset this mapping applies to', max_length=255)),
                ('source_file', models.CharField(blank=True, help_text='Original file path/name', max_length=500)),
                ('mapping_config', models.JSONField(default=dict, help_text='Type-specific mapping configuration')),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('active', 'Active')], default='draft', max_length=20)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('execution_stats', models.JSONField(default=dict, help_text='Statistics from last execution')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'mapping_type'], name='metadata_ma_organiz_1e991b_idx'), models.Index(fields=['source_dataset', 'validation_status'], name='metadata_ma_source__d7c426_idx')],
            },
        ),
    ]
