# Generated by Django 5.0.11 on 2025-06-18 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_alter_mapping_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mapping',
            name='metadata_ma_organiz_1e991b_idx',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='metadata_ma_source__d7c426_idx',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='mapping_type',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='source_dataset',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='source_file',
        ),
        migrations.AddField(
            model_name='mapping',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of what this mapping does'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='source_datasets',
            field=models.JSONField(default=list, help_text='List of datasets this mapping applies to'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='mapping_config',
            field=models.JSONField(default=dict, help_text='Flexible mapping configuration interpreted by GUI'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['organization_id', 'validation_status'], name='metadata_ma_organiz_f75d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['created_by', 'validation_status'], name='metadata_ma_created_94b7d1_idx'),
        ),
    ]
