# Generated by Django 5.0.11 on 2025-06-25 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_remove_mapping_metadata_ma_organiz_1e991b_idx_and_more'),
        ('users', '0003_alter_user_options_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': [('share_resource', 'Can share resource with others')]},
        ),
        migrations.AddField(
            model_name='resource',
            name='is_externally_linked',
            field=models.BooleanField(default=False, help_text='Whether this resource is referenced by users from other organizations'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this resource is visible to users from other organizations'),
        ),
        migrations.AddField(
            model_name='resource',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this resource belongs to (for permissions)', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['organization'], name='metadata_re_organiz_7e10dc_idx'),
        ),
    ]
