# Generated by Django 5.0.11 on 2025-06-25 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_alter_resource_options_resource_is_externally_linked_and_more'),
        ('users', '0004_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': [('share_resource', 'Can share resource with others'), ('can_approve_public_access', 'Can approve resources for public access')]},
        ),
        migrations.AddField(
            model_name='resource',
            name='is_public_approved',
            field=models.BooleanField(default=False, help_text='Has this resource been approved for public catalog display?'),
        ),
        migrations.AddField(
            model_name='resource',
            name='public_access_level',
            field=models.CharField(choices=[('private', 'Private - Organization only'), ('restricted', 'Restricted - Authenticated users only'), ('public', 'Public - Catalog display allowed')], default='private', help_text='Level of public access for this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='public_approved_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was approved for public access', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='public_approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this resource for public access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_approved_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['public_access_level', 'is_public_approved'], name='metadata_re_public__fb19d0_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['source', 'public_access_level'], name='metadata_re_source_d45659_idx'),
        ),
    ]
