# Generated by Django 5.0.11 on 2025-07-17 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_alter_mapping_source_datasets'),
        ('users', '0005_add_organization_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resource',
            name='unique_literal_value',
        ),
        migrations.AddField(
            model_name='resource',
            name='value_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of the value field for efficient uniqueness checking', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(condition=models.Q(('resource_type', 'LITERAL')), fields=('value_hash', 'language', 'datatype', 'name'), name='unique_literal_value_hash'),
        ),
    ]
