# Generated by Django 5.0.11 on 2025-07-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_remove_resource_unique_literal_value_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resource',
            name='value_idx',
        ),
    ]
