# Generated by Django 5.0.11 on 2025-07-18 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_remove_value_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='triple',
            index=models.Index(fields=['object', 'predicate'], name='metadata_tr_object__230fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='triple',
            index=models.Index(fields=['predicate'], name='metadata_tr_predica_1fa8dd_idx'),
        ),
    ]
