import pytest
from django.db import transaction
from arkumu.metadata.models.resource import Resource, ResourceType
from arkumu.common.hash_utils import generate_value_hash, generate_value_hash_and_normalize
from arkumu.common.uri_utils import normalize_string_nfc


@pytest.mark.django_db
def test_single_save_normalization_and_hashing():
    """Test that individual save() normalizes and generates hash correctly."""
    
    # Test with Unicode text that needs normalization
    # Using composed vs decomposed Unicode (é vs e + combining accent)
    original_value = "café"  # This might be decomposed form
    
    # Create resource using individual save (not bulk)
    resource = Resource(
        resource_type=ResourceType.LITERAL,
        value=original_value,
        datatype="xsd:string",
        language="de"
        # Note: No value_hash set - should be generated by save()
    )
    
    # Verify hash is not set before save
    assert resource.value_hash is None
    
    # Save the resource
    resource.save()
    
    # Verify value was normalized
    expected_normalized = normalize_string_nfc(original_value)
    assert resource.value == expected_normalized
    
    # Verify hash was generated by save() as fallback for individual saves
    assert resource.value_hash is not None
    assert len(resource.value_hash) == 64  # BLAKE2B 32-byte = 64 hex chars
    
    # Verify hash matches what centralized function would generate
    expected_hash = generate_value_hash(original_value)
    assert resource.value_hash == expected_hash


@pytest.mark.django_db  
def test_bulk_create_normalization_and_hashing():
    """Test that bulk_create properly normalizes and hashes values."""
    
    # Test values with Unicode normalization needs
    test_values = [
        "café",      # Might need normalization
        "résumé",    # Might need normalization  
        "naïve",     # Might need normalization
        "Hello World"  # Simple ASCII
    ]
    
    resources_to_create = []
    expected_hashes = []
    expected_normalized = []
    
    for value in test_values:
        # Use the efficient hash and normalize function
        value_hash, normalized_value = generate_value_hash_and_normalize(value)
        
        resource = Resource(
            value=normalized_value,
            value_hash=value_hash,
            resource_type=ResourceType.LITERAL,
            name=normalized_value[:100] if len(normalized_value) > 100 else normalized_value,
            datatype="http://www.w3.org/2001/XMLSchema#string",
            language="de",
            organization=None
        )
        
        resources_to_create.append(resource)
        expected_hashes.append(value_hash)
        expected_normalized.append(normalized_value)
    
    # Bulk create
    Resource.objects.bulk_create(resources_to_create)
    
    # Verify all resources were created with correct normalization and hashing
    created_resources = Resource.objects.filter(
        resource_type=ResourceType.LITERAL,
        language="de"
    )
    
    assert created_resources.count() == len(test_values)
    
    # Check each resource by finding it by hash (more reliable than ordering)
    for i, (original_value, expected_hash, expected_norm) in enumerate(zip(test_values, expected_hashes, expected_normalized)):
        resource = created_resources.get(value_hash=expected_hash)
        
        # Value should be normalized
        assert resource.value == expected_norm
        
        # Hash should be set correctly  
        assert resource.value_hash == expected_hash
        
        # Verify hash matches what we'd get from the centralized function
        assert resource.value_hash == generate_value_hash(original_value)


@pytest.mark.django_db
def test_hash_consistency_between_methods():
    """Test that individual save and bulk create produce identical results."""
    
    test_value = "café résumé"
    
    # Method 1: Individual save (if hash was generated)
    hash_individual = generate_value_hash(test_value)
    normalized_individual = normalize_string_nfc(test_value)
    
    # Method 2: Bulk create approach
    hash_bulk, normalized_bulk = generate_value_hash_and_normalize(test_value)
    
    # Should be identical
    assert hash_individual == hash_bulk
    assert normalized_individual == normalized_bulk


@pytest.mark.django_db
def test_unicode_normalization_prevents_duplicates():
    """Test that Unicode normalization prevents accidental duplicates."""
    
    # These should be considered the same after normalization
    value_composed = "café"     # é as single character
    value_decomposed = "cafe\u0301"  # e + combining acute accent
    
    # Both should normalize to the same thing
    hash1, norm1 = generate_value_hash_and_normalize(value_composed)
    hash2, norm2 = generate_value_hash_and_normalize(value_decomposed)
    
    assert hash1 == hash2, "Different Unicode representations should have same hash"
    assert norm1 == norm2, "Different Unicode representations should normalize identically"
    
    # Create first resource
    resource1 = Resource(
        value=norm1,
        value_hash=hash1,
        resource_type=ResourceType.LITERAL,
        name=norm1,
        datatype="xsd:string",
        language="de"
    )
    
    # Create second resource with same normalized content
    resource2 = Resource(
        value=norm2,
        value_hash=hash2,
        resource_type=ResourceType.LITERAL,
        name=norm2,
        datatype="xsd:string", 
        language="de"
    )
    
    # First should save fine
    resource1.save()
    
    # Second should violate unique constraint
    with pytest.raises(Exception):  # IntegrityError due to constraint
        resource2.save()


@pytest.mark.django_db
def test_bulk_create_performance_no_save_calls():
    """Test that bulk_create doesn't call save() method (performance test)."""
    
    # Create a custom Resource class to track save() calls
    save_call_count = 0
    
    original_save = Resource.save
    
    def counting_save(self, *args, **kwargs):
        nonlocal save_call_count
        save_call_count += 1
        return original_save(self, *args, **kwargs)
    
    # Monkey patch save method
    Resource.save = counting_save
    
    try:
        # Create multiple resources for bulk creation
        resources = []
        for i in range(5):
            value_hash, normalized_value = generate_value_hash_and_normalize(f"Test Value {i}")
            resource = Resource(
                value=normalized_value,
                value_hash=value_hash,
                resource_type=ResourceType.LITERAL,
                name=f"Test {i}",
                datatype="xsd:string",
                language="de"
            )
            resources.append(resource)
        
        # Bulk create should not call save()
        Resource.objects.bulk_create(resources)
        
        # Verify save() was never called
        assert save_call_count == 0, "bulk_create should not call save() method"
        
        # Verify resources were actually created
        assert Resource.objects.filter(
            resource_type=ResourceType.LITERAL,
            language="de"
        ).count() == 5
        
    finally:
        # Restore original save method
        Resource.save = original_save


@pytest.mark.django_db 
def test_long_value_name_truncation():
    """Test that long values get properly truncated for name field."""
    
    # Create a very long value
    long_value = "This is a very long value that should be truncated when used as the name field because names have a maximum length limit" * 3
    
    # Process it
    value_hash, normalized_value = generate_value_hash_and_normalize(long_value)
    
    # Create resource
    resource = Resource(
        value=normalized_value,
        value_hash=value_hash,
        resource_type=ResourceType.LITERAL,
        name=normalized_value[:100] if len(normalized_value) > 100 else normalized_value,
        datatype="xsd:string",
        language="de"
    )
    
    # Verify value is full length
    assert len(resource.value) > 100
    
    # Verify name is truncated to 100 chars
    assert len(resource.name) == 100
    assert resource.name == normalized_value[:100]
    
    # Save should work
    resource.save()
    
    # Verify in database
    saved_resource = Resource.objects.get(id=resource.id)
    assert len(saved_resource.value) > 100  # Full value preserved
    assert len(saved_resource.name) == 100   # Name truncated