# Generated by Django 5.0.11 on 2025-05-29 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(help_text='Name of the dataset being ingested', max_length=255)),
                ('organization', models.CharField(help_text='Organization slug/identifier', max_length=255)),
                ('s3_bucket', models.CharField(help_text='S3 bucket containing the CSV file', max_length=255)),
                ('s3_object_key', models.CharField(help_text='S3 object key/path to the CSV file', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delimiter', models.CharField(default=';', help_text='CSV delimiter', max_length=5)),
                ('has_quoted_fields', models.BooleanField(default=True)),
                ('base_uri', models.CharField(default='http://arkumu.org/data', max_length=512)),
                ('total_rows', models.IntegerField(default=0, help_text='Total rows in CSV file')),
                ('processed_rows', models.IntegerField(default=0, help_text='Number of rows processed')),
                ('successful_rows', models.IntegerField(default=0, help_text='Number of rows successfully ingested')),
                ('failed_rows', models.IntegerField(default=0, help_text='Number of rows that failed to ingest')),
                ('ingestion_stats', models.JSONField(blank=True, default=dict, help_text='Detailed ingestion statistics')),
                ('error_message', models.TextField(blank=True, help_text='Error message if ingestion failed')),
                ('task_id', models.CharField(blank=True, help_text='Background task ID for polling', max_length=255)),
                ('huey_task_id', models.CharField(blank=True, help_text='Huey task instance ID', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingest Session',
                'verbose_name_plural': 'Ingest Sessions',
                'indexes': [models.Index(fields=['user', 'status'], name='importer_in_user_id_332752_idx'), models.Index(fields=['organization', 'status'], name='importer_in_organiz_65f2b4_idx'), models.Index(fields=['created_at'], name='importer_in_created_9fee6d_idx'), models.Index(fields=['task_id'], name='importer_in_task_id_eb0f5f_idx')],
            },
        ),
    ]
