# Generated by Django 5.0.11 on 2025-07-23 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importer', '0001_initial'),
        ('metadata', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcommunication',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importpipelineerror',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_errors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errorcommunication',
            name='pipeline_error',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='importer.importpipelineerror'),
        ),
        migrations.AddField(
            model_name='ingestsession',
            name='mapping',
            field=models.ForeignKey(blank=True, help_text='Mapping configuration used for this import', null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.mapping'),
        ),
        migrations.AddField(
            model_name='ingestsession',
            name='organization',
            field=models.ForeignKey(help_text='Organization this ingestion belongs to', on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddField(
            model_name='ingestsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importtask',
            name='ingest_session',
            field=models.ForeignKey(help_text='Parent ingest session this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='import_tasks', to='importer.ingestsession'),
        ),
        migrations.AddField(
            model_name='importpipelineerror',
            name='ingest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_errors', to='importer.ingestsession'),
        ),
        migrations.AddField(
            model_name='fileprocessingissue',
            name='ingest_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_issues', to='importer.ingestsession'),
        ),
        migrations.AddField(
            model_name='executionphaseerror',
            name='ingest_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_errors', to='importer.ingestsession'),
        ),
        migrations.AddIndex(
            model_name='mappingvalidationissue',
            index=models.Index(fields=['mapping_id', 'severity'], name='importer_ma_mapping_cc646f_idx'),
        ),
        migrations.AddIndex(
            model_name='mappingvalidationissue',
            index=models.Index(fields=['organization', 'detected_at'], name='importer_ma_organiz_ca331b_idx'),
        ),
        migrations.AddIndex(
            model_name='mappingvalidationissue',
            index=models.Index(fields=['issue_type', 'severity'], name='importer_ma_issue_t_708e36_idx'),
        ),
        migrations.AddIndex(
            model_name='mappingvalidationissue',
            index=models.Index(fields=['validation_run_id'], name='importer_ma_validat_d6bdd3_idx'),
        ),
        migrations.AddIndex(
            model_name='errorcommunication',
            index=models.Index(fields=['pipeline_error', 'status'], name='importer_er_pipelin_850353_idx'),
        ),
        migrations.AddIndex(
            model_name='errorcommunication',
            index=models.Index(fields=['recipient', 'sent_at'], name='importer_er_recipie_90edd5_idx'),
        ),
        migrations.AddIndex(
            model_name='errorcommunication',
            index=models.Index(fields=['communication_type', 'status'], name='importer_er_communi_ab7e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestsession',
            index=models.Index(fields=['user', 'status'], name='importer_in_user_id_332752_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestsession',
            index=models.Index(fields=['organization', 'status'], name='importer_in_organiz_a81107_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestsession',
            index=models.Index(fields=['created_at'], name='importer_in_created_9fee6d_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestsession',
            index=models.Index(fields=['task_id'], name='importer_in_task_id_eb0f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='importtask',
            index=models.Index(fields=['task_id'], name='importer_im_task_id_f854c0_idx'),
        ),
        migrations.AddIndex(
            model_name='importtask',
            index=models.Index(fields=['ingest_session', 'status'], name='importer_im_ingest__a20238_idx'),
        ),
        migrations.AddIndex(
            model_name='importpipelineerror',
            index=models.Index(fields=['error_category', 'severity'], name='importer_im_error_c_e93a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='importpipelineerror',
            index=models.Index(fields=['ingest_session', 'occurred_at'], name='importer_im_ingest__fb66e8_idx'),
        ),
        migrations.AddIndex(
            model_name='importpipelineerror',
            index=models.Index(fields=['error_code', 'status'], name='importer_im_error_c_10dbfd_idx'),
        ),
        migrations.AddIndex(
            model_name='importpipelineerror',
            index=models.Index(fields=['mapping_id', 'dataset_name'], name='importer_im_mapping_5b66d9_idx'),
        ),
        migrations.AddIndex(
            model_name='importpipelineerror',
            index=models.Index(fields=['occurred_at'], name='importer_im_occurre_41313a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingissue',
            index=models.Index(fields=['ingest_session', 'issue_type'], name='importer_fi_ingest__173731_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingissue',
            index=models.Index(fields=['file_path'], name='importer_fi_file_pa_10c2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingissue',
            index=models.Index(fields=['detected_at'], name='importer_fi_detecte_1cec79_idx'),
        ),
        migrations.AddIndex(
            model_name='executionphaseerror',
            index=models.Index(fields=['ingest_session', 'phase'], name='importer_ex_ingest__b8b094_idx'),
        ),
        migrations.AddIndex(
            model_name='executionphaseerror',
            index=models.Index(fields=['phase', 'error_type'], name='importer_ex_phase_9f91d6_idx'),
        ),
        migrations.AddIndex(
            model_name='executionphaseerror',
            index=models.Index(fields=['occurred_at'], name='importer_ex_occurre_e15a59_idx'),
        ),
    ]
