# Generated by Django 5.0.11 on 2025-07-09 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportPipelineError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_code', models.CharField(help_text='Unique error code for categorization', max_length=50)),
                ('error_type', models.CharField(help_text='Python exception type or error class', max_length=100)),
                ('error_message', models.TextField(help_text='Human-readable error message')),
                ('error_category', models.CharField(choices=[('validation', 'Validation Error'), ('file_processing', 'File Processing Error'), ('data_transformation', 'Data Transformation Error'), ('execution', 'Execution Error'), ('storage', 'Storage Error'), ('mapping', 'Mapping Error'), ('system', 'System Error')], default='system', max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Information')], default='error', max_length=10)),
                ('mapping_id', models.UUIDField(blank=True, help_text='Associated mapping ID', null=True)),
                ('dataset_name', models.CharField(blank=True, help_text='Dataset being processed', max_length=255)),
                ('file_path', models.CharField(blank=True, help_text='File path causing the error', max_length=512)),
                ('row_number', models.IntegerField(blank=True, help_text='Row number in CSV file', null=True)),
                ('column_name', models.CharField(blank=True, help_text='Column name causing error', max_length=100)),
                ('stack_trace', models.TextField(blank=True, help_text='Full stack trace')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('first_occurrence', models.DateTimeField(auto_now_add=True)),
                ('last_occurrence', models.DateTimeField(auto_now=True)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='new', max_length=15)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about error resolution')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_errors', to=settings.AUTH_USER_MODEL)),
                ('ingest_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_errors', to='importer.ingestsession')),
            ],
            options={
                'verbose_name': 'Import Pipeline Error',
                'verbose_name_plural': 'Import Pipeline Errors',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communication_type', models.CharField(choices=[('email', 'Email Notification'), ('ui_alert', 'UI Alert'), ('slack', 'Slack Notification'), ('log_entry', 'Log Entry'), ('dashboard', 'Dashboard Update')], max_length=15)),
                ('recipient', models.EmailField(help_text='Email address of recipient', max_length=254)),
                ('subject', models.CharField(help_text='Communication subject', max_length=255)),
                ('message', models.TextField(help_text='Communication message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('acknowledged', 'Acknowledged')], default='pending', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, help_text='External service message ID', max_length=255)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Communication error details')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_communications', to=settings.AUTH_USER_MODEL)),
                ('pipeline_error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='importer.importpipelineerror')),
            ],
            options={
                'verbose_name': 'Error Communication',
                'verbose_name_plural': 'Error Communications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MappingValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping_id', models.UUIDField(help_text='Associated mapping ID')),
                ('mapping_name', models.CharField(help_text='Mapping name for reference', max_length=255)),
                ('organization', models.CharField(help_text='Organization code', max_length=100)),
                ('issue_type', models.CharField(choices=[('missing_field', 'Missing Required Field'), ('invalid_type', 'Invalid Data Type'), ('invalid_reference', 'Invalid Reference'), ('circular_dependency', 'Circular Dependency'), ('inconsistent_config', 'Inconsistent Configuration'), ('performance_warning', 'Performance Warning'), ('best_practice', 'Best Practice Violation')], max_length=30)),
                ('severity', models.CharField(choices=[('blocker', 'Blocker'), ('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('info', 'Information')], max_length=10)),
                ('issue_code', models.CharField(help_text='Unique issue code', max_length=50)),
                ('issue_message', models.TextField(help_text='Human-readable issue description')),
                ('dataset_name', models.CharField(blank=True, help_text='Dataset with issue', max_length=255)),
                ('column_name', models.CharField(blank=True, help_text='Column with issue', max_length=100)),
                ('field_path', models.CharField(blank=True, help_text='JSON path to problematic field', max_length=255)),
                ('expected_value', models.TextField(blank=True, help_text='What was expected')),
                ('actual_value', models.TextField(blank=True, help_text='What was found')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context')),
                ('remediation_suggestion', models.TextField(blank=True, help_text='Suggested fix')),
                ('documentation_link', models.URLField(blank=True, help_text='Link to relevant documentation')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('validation_run_id', models.UUIDField(blank=True, help_text='ID of validation run', null=True)),
            ],
            options={
                'verbose_name': 'Mapping Validation Issue',
                'verbose_name_plural': 'Mapping Validation Issues',
                'ordering': ['-detected_at', 'severity'],
                'indexes': [models.Index(fields=['mapping_id', 'severity'], name='importer_ma_mapping_cc646f_idx'), models.Index(fields=['organization', 'detected_at'], name='importer_ma_organiz_ca331b_idx'), models.Index(fields=['issue_type', 'severity'], name='importer_ma_issue_t_708e36_idx'), models.Index(fields=['validation_run_id'], name='importer_ma_validat_d6bdd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionPhaseError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('validation', 'Validation Phase'), ('file_download', 'File Download Phase'), ('data_processing', 'Data Processing Phase'), ('entity_creation', 'Entity Creation Phase'), ('literal_processing', 'Literal Processing Phase'), ('relationship_processing', 'Relationship Processing Phase'), ('context_processing', 'Context Processing Phase'), ('finalization', 'Finalization Phase')], max_length=25)),
                ('phase_step', models.CharField(blank=True, help_text='Specific step within phase', max_length=100)),
                ('error_type', models.CharField(help_text='Python exception type', max_length=100)),
                ('error_message', models.TextField(help_text='Error message')),
                ('stack_trace', models.TextField(blank=True, help_text='Stack trace')),
                ('dataset_name', models.CharField(blank=True, max_length=255)),
                ('batch_info', models.JSONField(blank=True, default=dict, help_text='Batch processing context')),
                ('rows_affected', models.IntegerField(default=0, help_text='Number of rows affected')),
                ('can_continue', models.BooleanField(default=False, help_text='Can execution continue?')),
                ('recovery_strategy', models.CharField(blank=True, help_text='Suggested recovery strategy', max_length=100)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('ingest_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_errors', to='importer.ingestsession')),
            ],
            options={
                'verbose_name': 'Execution Phase Error',
                'verbose_name_plural': 'Execution Phase Errors',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['ingest_session', 'phase'], name='importer_ex_ingest__b8b094_idx'), models.Index(fields=['phase', 'error_type'], name='importer_ex_phase_9f91d6_idx'), models.Index(fields=['occurred_at'], name='importer_ex_occurre_e15a59_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileProcessingIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Full path to problematic file', max_length=512)),
                ('file_name', models.CharField(help_text='File name', max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('issue_type', models.CharField(choices=[('file_not_found', 'File Not Found'), ('file_corrupted', 'File Corrupted'), ('encoding_error', 'Encoding Error'), ('format_error', 'Format Error'), ('size_limit', 'Size Limit Exceeded'), ('permission_denied', 'Permission Denied'), ('network_error', 'Network Error'), ('parsing_error', 'Parsing Error')], max_length=20)),
                ('issue_message', models.TextField(help_text='Detailed issue description')),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Technical error details')),
                ('detected_encoding', models.CharField(blank=True, help_text='Detected file encoding', max_length=50)),
                ('expected_format', models.CharField(blank=True, help_text='Expected file format', max_length=50)),
                ('recovery_attempted', models.BooleanField(default=False)),
                ('recovery_successful', models.BooleanField(default=False)),
                ('recovery_notes', models.TextField(blank=True, help_text='Recovery attempt details')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('ingest_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_issues', to='importer.ingestsession')),
            ],
            options={
                'verbose_name': 'File Processing Issue',
                'verbose_name_plural': 'File Processing Issues',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['ingest_session', 'issue_type'], name='importer_fi_ingest__173731_idx'), models.Index(fields=['file_path'], name='importer_fi_file_pa_10c2ef_idx'), models.Index(fields=['detected_at'], name='importer_fi_detecte_1cec79_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='importpipelineerror',
            index=models.Index(fields=['error_category', 'severity'], name='importer_im_error_c_e93a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='importpipelineerror',
            index=models.Index(fields=['ingest_session', 'occurred_at'], name='importer_im_ingest__fb66e8_idx'),
        ),
        migrations.AddIndex(
            model_name='importpipelineerror',
            index=models.Index(fields=['error_code', 'status'], name='importer_im_error_c_10dbfd_idx'),
        ),
        migrations.AddIndex(
            model_name='importpipelineerror',
            index=models.Index(fields=['mapping_id', 'dataset_name'], name='importer_im_mapping_5b66d9_idx'),
        ),
        migrations.AddIndex(
            model_name='importpipelineerror',
            index=models.Index(fields=['occurred_at'], name='importer_im_occurre_41313a_idx'),
        ),
        migrations.AddIndex(
            model_name='errorcommunication',
            index=models.Index(fields=['pipeline_error', 'status'], name='importer_er_pipelin_850353_idx'),
        ),
        migrations.AddIndex(
            model_name='errorcommunication',
            index=models.Index(fields=['recipient', 'sent_at'], name='importer_er_recipie_90edd5_idx'),
        ),
        migrations.AddIndex(
            model_name='errorcommunication',
            index=models.Index(fields=['communication_type', 'status'], name='importer_er_communi_ab7e5b_idx'),
        ),
    ]
