# Generated by Django 5.0.11 on 2025-07-12 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_create_error_tracking_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestsession',
            name='file_paths',
            field=models.JSONField(blank=True, default=list, help_text='List of file paths for multi-file imports'),
        ),
        migrations.AddField(
            model_name='ingestsession',
            name='mapping_id',
            field=models.IntegerField(blank=True, help_text='ID of the mapping configuration used for this import', null=True),
        ),
        migrations.AlterField(
            model_name='ingestsession',
            name='dataset_name',
            field=models.CharField(blank=True, help_text='Name of the dataset being ingested', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ingestsession',
            name='s3_bucket',
            field=models.CharField(blank=True, help_text='S3 bucket containing the CSV file', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ingestsession',
            name='s3_object_key',
            field=models.CharField(blank=True, help_text='S3 object key/path to the CSV file', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ingestsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
