# Generated by Django 5.0.11 on 2025-07-12 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_ingestsession_file_paths_ingestsession_mapping_id_and_more'),
        ('users', '0005_add_organization_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ingestsession',
            new_name='importer_in_organiz_a81107_idx',
            old_name='importer_in_organiz_65f2b4_idx',
        ),
        migrations.AlterField(
            model_name='ingestsession',
            name='organization',
            field=models.ForeignKey(help_text='Organization this ingestion belongs to', on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
    ]
