# Generated by Django 5.0.11 on 2025-07-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_rename_importer_in_organiz_65f2b4_idx_importer_in_organiz_a81107_idx_and_more'),
        ('metadata', '0011_alter_mapping_source_datasets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingestsession',
            name='mapping_id',
        ),
        migrations.AddField(
            model_name='ingestsession',
            name='mapping',
            field=models.ForeignKey(blank=True, help_text='Mapping configuration used for this import', null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.mapping'),
        ),
    ]
