# Generated by Django 5.0.11 on 2025-07-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_remove_ingestsession_mapping_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestsession',
            name='progress_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ingestsession',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingestsession',
            name='progress_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
