# Generated by Django 5.0.11 on 2025-07-18 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_ingestsession_progress_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(help_text='Name of the dataset being imported', max_length=255)),
                ('file_path', models.CharField(help_text='S3 file path for this dataset', max_length=512)),
                ('task_id', models.CharField(help_text='Unique task ID for progress tracking', max_length=255, unique=True)),
                ('huey_task_id', models.CharField(blank=True, help_text='Huey task instance ID', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rows_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('ingest_session', models.ForeignKey(help_text='Parent ingest session this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='import_tasks', to='importer.ingestsession')),
            ],
            options={
                'db_table': 'importer_import_task',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['task_id'], name='importer_im_task_id_f854c0_idx'), models.Index(fields=['ingest_session', 'status'], name='importer_im_ingest__a20238_idx')],
            },
        ),
    ]
