# Generated by Django 5.0.11 on 2025-07-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0008_add_skipped_datasets_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
